language: haxe

haxe:
  - "3.2.0"

before_install:
  # Setup Haxe and continue
  - haxelib install format > /dev/null
  - haxelib install hxcpp > /dev/null
  - haxelib install lime > /dev/null
  - haxelib list
  - haxelib dev extension-gamecenter $(pwd)
  - gem install travis-artifacts --no-ri --no-rdoc

script:
  - haxelib run lime rebuild extension-gamecenter ios
