language: objective-c

env:
 global:
  - ARTIFACTS_AWS_REGION=us-west-2
  - ARTIFACTS_S3_BUCKET=gamecenter-artifacts
  - secure: "LMd6UhjDEUEnOvWIwyvTGvdPlwC5s0FsXGOrtNd3B0L1ylZVH98uVIf7hrxocQ8gmcfV4tOT+3ObkiUvgD93HPKyjPBGLx8VzveZTdmp9DDFzVTrLpPnv7ynnW5F6r2K3Ohtu67ZJNy0bZ8GfLiSfgV1PL/dRfA7oIQVMbKebN8="
  - secure: "NYXsXEKm8tbF7NDEMK2pmXmiykaAB6dv7tRRxvli8xkPFUzAf43slbtkoMo0pOAtaVsHZUndVBxHzOastwqxSM5k1Zp3sCx0GCZWvSLAj7yU/UVYa1kKoWWGZMTy4gEZMvKV9YKGoIgtNvXlpUQTDa3b7pNSnkYIq5EtKR7zCBU="

before_install:
  # Use Lime's 64 Mac Neko
  - git clone https://github.com/openfl/lime ~/lime
  - pushd ~/lime
  - git submodule init
  - git submodule update
  - popd

  # Use Lime's Mac 64bit Neko
  - sudo ln -s ~/lime/templates/neko/bin/neko-mac64 /usr/bin/neko  
  - sudo ln -s ~/lime/templates/neko/ndll/mac64/libneko.dylib /usr/lib/libneko.dylib
  - sudo ln -s ~/lime/templates/neko/ndll/mac64/regexp.ndll /usr/lib/regexp.ndll
  - sudo ln -s ~/lime/templates/neko/ndll/mac64/sqlite.ndll /usr/lib/sqlite.ndll
  - sudo ln -s ~/lime/templates/neko/ndll/mac64/std.ndll /usr/lib/std.ndll
  - sudo ln -s ~/lime/templates/neko/ndll/mac64/zlib.ndll /usr/lib/zlib.ndll

  # Setup Haxe and continue
  - wget -c http://haxe.org/file/haxe-3.1.3-osx.tar.gz
  - sudo mkdir /usr/lib/haxe
  - sudo tar xvzf haxe-3.1.3-osx.tar.gz -C /usr/lib/haxe --strip-components=1
  - sudo ln -s /usr/lib/haxe/haxe /usr/bin/haxe
  - sudo ln -s /usr/lib/haxe/haxelib /usr/bin/haxelib
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install format
  - haxelib install hxcpp
  - git clone https://github.com/openfl/hxlibc ~/hxlibc
  - haxelib dev hxlibc ~/hxlibc
# - git clone https://github.com/openfl/lime ~/lime
  - haxelib dev lime ~/lime
  - haxelib dev gamecenter $(pwd)
  - gem install travis-artifacts --no-ri --no-rdoc

script:
  - haxelib run lime rebuild gamecenter ios

after_success:
  - export COMMIT_NAME=`git describe --tags`
  - cd ..
  - zip -r gamecenter-$COMMIT_NAME.zip gamecenter/ -x *.git* -x *.DS_Store* -x *project/obj* -x *project/all_objs*
  - travis-artifacts upload --path gamecenter-$COMMIT_NAME.zip --target-path artifacts
  - wget -qO- http://www.openfl.org/gamecenter-post-hook.php?commit=$COMMIT_NAME
