language: objective-c

env:
 global:
  - ARTIFACTS_AWS_REGION=us-west-2
  - ARTIFACTS_S3_BUCKET=gamecenter-artifacts
  - secure: "LMd6UhjDEUEnOvWIwyvTGvdPlwC5s0FsXGOrtNd3B0L1ylZVH98uVIf7hrxocQ8gmcfV4tOT+3ObkiUvgD93HPKyjPBGLx8VzveZTdmp9DDFzVTrLpPnv7ynnW5F6r2K3Ohtu67ZJNy0bZ8GfLiSfgV1PL/dRfA7oIQVMbKebN8="
  - secure: "NYXsXEKm8tbF7NDEMK2pmXmiykaAB6dv7tRRxvli8xkPFUzAf43slbtkoMo0pOAtaVsHZUndVBxHzOastwqxSM5k1Zp3sCx0GCZWvSLAj7yU/UVYa1kKoWWGZMTy4gEZMvKV9YKGoIgtNvXlpUQTDa3b7pNSnkYIq5EtKR7zCBU="

before_install:

  # Setup Haxe and continue
  - wget -c http://haxe.org/download/file/3.2.1/haxe-3.2.1-osx.tar.gz
  - sudo mkdir /usr/local/lib/haxe
  - sudo tar xvzf haxe-3.2.1-osx.tar.gz -C /usr/local/lib/haxe --strip-components=1
  - sudo ln -s /usr/local/lib/haxe/haxe /usr/bin/haxe
  - sudo ln -s /usr/local/lib/haxe/haxelib /usr/bin/haxelib
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install format
  - haxelib install hxcpp
  - haxelib install lime
  - haxelib dev extension-gamecenter $(pwd)
  - gem install travis-artifacts --no-ri --no-rdoc

script:
  - haxelib run lime rebuild extension-gamecenter ios

after_success:
  - export COMMIT_NAME=`git describe --tags`
  - cd ..
  - zip -r gamecenter-$COMMIT_NAME.zip gamecenter/ -x *.git* -x *.DS_Store* -x *project/obj* -x *project/all_objs*
  - travis-artifacts upload --path gamecenter-$COMMIT_NAME.zip --target-path artifacts
  - wget -qO- http://www.openfl.org/gamecenter-post-hook.php?commit=$COMMIT_NAME
